runtime: python27
api_version: 1
threadsafe: true
service: 'app'

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /(.*)
  static_files: dist/index.html
  upload: dist/(.*)